### ISSUE TITLE
BankNote serial number isn't unique

### ISSUE THREAD

**Issue by bokherus** [OOP2018/coinpurse-Raksani#17]
```java
    /**
     * Make a Valuable (or BankNote or whatever) using requested value.
     */
    private Valuable makeMoney(double value) {
        MoneyFactory.setFactory(new ThaiMoneyFactory());
        MoneyFactory moneyFactory = MoneyFactory.getInstance();
        try {
            return MoneyFactory.getInstance().createMoney(value);
        } catch (IllegalArgumentException e) {
            System.out.println("Cannot create money factory.");
        }
        return null;
    }

```

From the code above, you call 
`MoneyFactory.setFactory(new ThaiMoneyFactory());`
so, every time you call the method `makeMoney(someValue)` you set the factory to a new instance of `ThaiMoneyFactory`. You should use the same factory to create Money or make `nextSerialNumber` in factory become static do that the value is shared among instances.

**Comment by Raksani** [comment]
Done.

I would like to ask something. From SupalukBenz repo, there's no repo but her score is 8.
If she can improve her code and get more score.
